P8130 hw6
================
Chenxin Zhang
12/2/2020

## Problem 1.1 Create a correlation matrix

``` r
matrix = pat_df %>% 
  cor() 
matrix
```

    ##              satisfaction    age severity anxiety
    ## satisfaction        1.000 -0.787   -0.603  -0.645
    ## age                -0.787  1.000    0.568   0.570
    ## severity           -0.603  0.568    1.000   0.671
    ## anxiety            -0.645  0.570    0.671   1.000

Satisfaction is negatively correlated with age, severity, and anxiety.
Age is positively correlated with severity and anxiety. Severity ia
positively correlated with anxiety. The correlations of age and
severity, age and anxiety are positive which are 0.57 and 0.67. If the
three predictor were included in the model, there will be
multicollinearity which will result in a decrease in significance.

## Problem 1.2 Fit a multiple regression model including all three predictors

``` r
pat_df_lm =
  lm(satisfaction ~ .,data = pat_df)
```

We conduct the **ANOVA test for MLR**, with the number of predictors of
p = 3, and n = 46. Let 1 denotes age, 2 denotes severity, and 3 denotes
anxiety

**hypothesis: **

\(H_0~:~\beta_1=\beta_2=\beta_3 = 0\)

$ H\_1$ : at least one of the coefficient not equal to 0  
The model we fit is:  
\[statisfaction=158.4913-1.1416age-0.4420severity-13.4702anxiety\]
**statistics**

 \[F = \frac{MSR}{MSE}= \frac{SSR/p}{SSE(n-p-1)}=30.1\]
 \(F_{1-0.05,3,46-3-1}=2.827\) **Decision Rule**
 \(Reject ~ H_0 ~ if ~ F>F_{1-\alpha,p,n-p-1}\)

 \(Fail ~ reject ~ H_0 ~ if ~F<F_{1-\alpha,p,n-p-1}\)

**Interpretation**  Since F\_statistics equal to
30.1\>\(F_{1-0.05,3,46-3-1}=2.827\), at 0.05 confidence level, we reject
the null hypothesis and conclude that at least one predictor have
coefficent not equal to 0.

## Problem 1.3 Show the regression results for all estimated slope coefficients with 95% CIs. Interpret the coefficient and 95% CI associated with ‘severity of illness’.

``` r
confint(pat_df_lm)
```

    ##              2.5 %  97.5 %
    ## (Intercept) 121.91 195.071
    ## age          -1.58  -0.708
    ## severity     -1.43   0.551
    ## anxiety     -27.80   0.858

  With one unit change of severity of disease, we are 95% confident that
the mean change of patients’ satisfaction score will between -1.43 and
0.55.

## Problem 1.4 Obtain an interval estimate for a new patient’s satisfaction with the following characteristics:Age=35, Severity=42, Anxiety=2.1. Interpret the interval. (2p)

|  fit |  lwr |  upr |
| ---: | ---: | ---: |
| 71.7 | 50.1 | 93.3 |

 For a patient with age 35, severity of illness of 42 and anxiety level
of 2.1, We are 95% confident that the predicted mean patient’s
satisfaction score will between 50.1 nd 93.3.

## Problem 1.5.a) Test whether ‘anxiety level’ can be dropped from the regression model, given the other two covariates are retained.

We use the ANOVA partical F-test in MLR to test whether anxiety level is
significant or not in the regression model.  **hypothesis: **
 \(H_0~:~\beta_{anxiety} = 0\)

 \(H_1~:~\beta_{anxiety} \ne 0\)

 model 1: without anxiety as predictor
\[statisfaction=\beta_{0}+\beta_{1}age+\beta_{2}severity+ \varepsilon_{i}\]
 model 2: with anxirty as predictor
\[statisfaction=\beta_{0}+\beta_{1}age+\beta_{2}severity+\beta_{3}anciety+\varepsilon_{i}\]
 **statistics**
\[F = \frac{SSR_{L}-SSR_{S}/(df_{L}-dS_{S})}{SSE_{L}/df_{L}}=30.1  \]
 \[F_{1-\alpha,df_L - df_S,df_L} = 4.073\]

``` r
pat_df_lm2 = lm(satisfaction ~ age + severity, pat_df)
anova(pat_df_lm,pat_df_lm2)
```

    ## Analysis of Variance Table
    ## 
    ## Model 1: satisfaction ~ age + severity + anxiety
    ## Model 2: satisfaction ~ age + severity
    ##   Res.Df  RSS Df Sum of Sq   F Pr(>F)  
    ## 1     42 4249                          
    ## 2     43 4613 -1      -364 3.6  0.065 .
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

``` r
qf(0.95,1,42)#4.07
```

    ## [1] 4.07

**Decision Rule**
 \(Reject ~ H_0 ~ if ~ F>F_{1-\alpha,df_L - df_S,df_L}\)

 \(Fail ~ reject ~ H_0 ~ if ~F<F_{1-\alpha, df_L - df_S,df_L}\)

**Interpretation**  Since F\_statistics equal to 30.1\<4.073, at 0.05
confidence level, we fail to reject the null hypothesis and conclude
model 2 is not superior, which means that anxity can be dropped out from
the regression model.

## Problem 1.5.b) How are R2/R2-adjusted impacted by the action that you took in part 5-a)?

    ## # A tibble: 2 x 3
    ##   Model                    r_squared adj_r_squared
    ##   <chr>                        <dbl>         <dbl>
    ## 1 Model 1(without anxiety)     0.655         0.639
    ## 2 Model 2(with anxiety)        0.682         0.659

 Both values will decrease. Model 2 has larger r\_squared and
adj\_r\_squared than model 1, the reason is that model 2 has one more
predictor which can decrease the sum of square error. However, the
percentage of increase by add anxiety as predictor is small approsimatly
equal to 4% for r\_squared and 3% for adj\_r\_squared, so we can drop
the anxiety predictor from model 2.

## Problem 2.1 Is there a crude association between BMI and serum estradiol?

**1. a scatter plot with the overlaid regression line.**

**1.2 Provide the summary regression output**
